name: haystack-platform
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # API dependencies
    - fastapi==0.75.1
    - uvicorn==0.17.6
    - pydantic==1.9.0
    - sqlalchemy==1.4.35
    - sqlalchemy-views==0.3.1
    - psycopg2-binary>=2.9.5
    - starlette==0.17.1
    - gunicorn==21.2.0
    
    # Simulator dependencies (using newer versions where conflicts exist)
    - pandas>=1.5.0
    - numpy>=1.24.0
    - PyYAML>=6.0
    - rich>=13.0.0
    - APScheduler>=3.10.0
    - python-dateutil>=2.8.0
    - pytz>=2023.3
    
    # Authentication & AWS
    - PyJWT==2.6.0
    - boto3
    - cryptography==41.0.7
    
    # HTTP & networking
    - requests
    - urllib3==1.26.9
    - anyio==3.5.0
    - h11==0.13.0
    - idna==3.3
    - sniffio==1.2.0
    
    # Configuration & utilities
    - python-dotenv==1.0.1
    - json-cfg==0.4.2
    - click==8.1.2
    - openpyxl
    
    # ANTLR for parsing
    - antlr4-python3-runtime==4.10
    
    # Development tools
    - flake8==4.0.1
    - autopep8==1.6.0
    - pyright==1.1.235
    - black>=23.0.0
    - mypy>=1.0.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    
    # Other utilities
    - kwonly-args==1.0.10
    - mccabe==0.6.1
    - nodeenv==1.6.0
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - toml==0.10.2
    - typing_extensions==4.1.1
    - asgiref==3.5.0
    - greenlet>=2.0.0