# Database configuration for Docker local testing
# This config assumes you're running docker-compose and connecting from host

# TimescaleDB - Building Data (entities, tags, time-series)
database:
  host: localhost        # Use 'timescaledb' if running simulator inside docker
  port: 5432
  database: datakwip
  user: datakwip_user
  password: datakwip_password

# PostgreSQL - Simulator State (operational state only)
state_database:
  host: localhost        # Use 'statedb' if running simulator inside docker
  port: 5433
  database: simulator_state
  user: simulator_user
  password: simulator_password

organization:
  name: "Docker Test Organization"
  key: "docker_test"

tables:
  value_table: "values_docker_test"
  current_table: "values_docker_test_current"

# Alternative: Use environment variables
# DATABASE_URL: postgresql://datakwip_user:datakwip_password@localhost:5432/datakwip
# STATE_DB_URL: postgresql://simulator_user:simulator_password@localhost:5433/simulator_state
